# Generated by Django 4.0.2 on 2022-03-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerudagramApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nerudagrammodel',
            name='lpp',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.AlterField(
            model_name='nerudagrammodel',
            name='mwpl',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.AlterField(
            model_name='nerudagrammodel',
            name='ngram',
            field=models.IntegerField(choices=[('UN', 'monograma'), ('BI', 'bigrama'), ('TR', 'trigrama'), ('FO', 'tetragrama')]),
        ),
        migrations.AlterField(
            model_name='nerudagrammodel',
            name='wpt',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
