# Generated by Django 4.0.2 on 2022-03-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerudagramApp', '0002_alter_nerudagrammodel_lpp_alter_nerudagrammodel_mwpl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nerudagrammodel',
            name='ngram',
            field=models.IntegerField(choices=[('monograma', 1), ('bigrama', 2), ('trigrama', 3), ('tetragrama', 4)]),
        ),
    ]
