# Generated by Django 4.0.2 on 2022-03-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerudagramApp', '0004_alter_nerudagrammodel_ngram'),
    ]

    operations = [
        migrations.AddField(
            model_name='nerudagrammodel',
            name='poem',
            field=models.CharField(blank=True, max_length=64000),
        ),
        migrations.AlterField(
            model_name='nerudagrammodel',
            name='lpp',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Cantidad de versos del poema'),
        ),
        migrations.AlterField(
            model_name='nerudagrammodel',
            name='mwpl',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Cantidad máxima de palabras por verso'),
        ),
        migrations.AlterField(
            model_name='nerudagrammodel',
            name='ngram',
            field=models.IntegerField(choices=[(1, 'monograma'), (2, 'bigrama'), (3, 'trigrama'), (4, 'tetragrama')], verbose_name='Modelo de N-Grama'),
        ),
        migrations.AlterField(
            model_name='nerudagrammodel',
            name='wpt',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Cantidad de palabras en el título'),
        ),
    ]
