# Generated by Django 4.0.2 on 2022-03-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerudagramApp', '0005_nerudagrammodel_poem_alter_nerudagrammodel_lpp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nerudagrammodel',
            name='title',
            field=models.CharField(blank=True, max_length=126),
        ),
    ]
