# Generated by Django 4.0.2 on 2022-03-05 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nerudagramApp', '0006_nerudagrammodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='NerudagramHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=126)),
                ('poem', models.CharField(blank=True, max_length=64000)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='nerudagramApp.nerudagrammodel')),
            ],
        ),
    ]
